[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
linea-sepolia = "${RPC_URL_LINEA}"

[etherscan]
linea-sepolia = { key = "${LINEASCAN_API_KEY}", url = "https://api-sepolia.lineascan.build/api" }
mantle-sepolia = { key = "", url = "https://explorer.sepolia.mantle.xyz/api" }
opbnb-testnet = { key = "${OPBNBSCAN_API_KEY}", url = "https://api-opbnb-testnet.bscscan.com/api" }